### ISSUE TITLE
In plan9 cat is "argv0" correct?

### ISSUE THREAD

**Issue by Gumnos** [pete/cats#2]
In the plan9 version of cat, it has

    argv0 = "cat";

but `argv0` is never defined nor used for anything.  Was this copied correctly from the source?  I suspect it was supposed to be `argv[0]` to set the filename. (I don't have plan9 sources at hand to check)

**Comment by pete** [comment]
It was correctly copied, and it is used, but the usage isn't readily apparent.  The declaration of `argv0` as a global is in `libc.h` (https://github.com/0intro/plan9/blob/master/sys/include/libc.h#L718), and `sysfatal` makes use of it for its error message.  Other programs in Plan 9 use it in place of `argv[0]` for scope convenience, and it often gets assigned like `argv0 = argv[0]`.  (Just a WAG, but I'd speculate that having it as a global also helps with identifying random core files.)  There is some slightly more involved usage of `argv0` (e.g., https://github.com/0intro/plan9/blob/master/sys/src/cmd/aux/usage.c) but it's usually just set at the beginning and then not explicitly used.

I don't have the exact history handy (you might want to try 9fans) but it doesn't seem to appear in the fabled (and only recently released) Unix Research Version 10 libc (https://www.tuhs.org/Archive/Distributions/Research/Dan_Cross_v10/ has tarballs), though there's some usage of `argv0` resembling Plan 9's usage in the interactive SCSI shell for the WORM system.

If you aren't able to check out the source code, you can find it in @0intro's Plan 9 repo here: https://github.com/0intro/plan9/blob/master/sys/src/cmd/cat.c.  The 9front version (http://code.9front.org/hg/plan9front/file/8ae76288951f/sys/src/cmd/cat.c) and the P9P version (https://9fans.github.io/usr/local/plan9/src/cmd/) are identical.

**Comment by Gumnos** [comment]
Ah, okay. Just seemed odd but your explanation makes it less strange. Thanks.
