### ISSUE TITLE
Toybox and Sbase cat?

### ISSUE THREAD

**Issue by oliverkwebb** [pete/cats#4]
From https://github.com/landley/toybox/blob/master/toys/posix/cat.c and https://git.suckless.org/sbase/file/cat.c.html respectively

Toybox is the main set of command line utilities in android, and sbase is the suckless projects version of core system utilities

**Comment by pete** [comment]
Oh, awesome!  Thanks!

**Comment by pete** [comment]
I think (haven't checked yet) that the suckless base is p9p, or I recall them doing something like enough p9p to run werc.

**Comment by oliverkwebb** [comment]
They do have https://git.suckless.org/9base/, but I'm pretty sure https://git.suckless.org/sbase/ is a different project

**Comment by pete** [comment]
Added!  Thanks very much!
